### PR TITLE
Feature: Toolcheck V2

### PR DESCRIPTION
**Pull request by aaron-sgy**
# New
- Added a new tab in GUI that shows Parts & Tools that are unecessary. 
- Also show Tools that are needed for the step, if tools are necessary for that specific step. It will check if the tools is being used and update it with a checkmark if it is detected.
- Step1-7 All have unwanted/wanted detections classes specified.
- The Step class now has a new parameter `tools`, this stores a list of necessary tools for that step.

## New functions in `GUI_detect.py`
- `build_tools`
  - Build the Tklabel for each tools necessary for the step
  - save those tklabels into a list called `tools_list[]`   
-  `update_tools`
  - updates the tklabel for necessary tools for the step to a green color and add a check mark when it is detected
- `update_unwant_tools`
  - for any unwnated parts/tools detected, make a new tklabel and show it on the GUI with a red color and a `X,' and then store them into a list named `unwant_tools_tkinter_list`
  - If the unwanted class is no longer detected it will be removed from the list and forgotten so it doesn't show on the GUI anymore
- `clear_tools`
  - clear the `tools_list` that stores tklabel for wanted tools
  -  clear the `unwant_tools_tkinter_list` that stores tklabel for unwanted tools/parts
 ## New functions in`logic_tools.py`
- `get_keys_from_value`
  - simply get the key with its value on a dictionary
  - doesn't throw exception when value is not found but just return None
  - if there are multiple keys that have the same value, it will return a list of keys that has that value 

# Minor Change
class_index is no longer in `logic_tools.py` it is relocated into `shared.py` for convenience and consistency sake

# Potential Issue
A new substep is added for step 7 for detecting the lockring wrench. This is hardcoded by adding 1 to each substep index.

### CODE REVIEW

**Comment by sophieqguan** [comment]
Everything seems to work, but I think it might be more intuitive/helpful if we list out the necessary tools under the Tool tab and mark it green when it is detected.

**Comment by aaron-sgy** [comment]
The only tool required is Step 3 and Step 7. This should already have been implemented. Is it not showing correctly?

**Comment by aaron-sgy** [comment]
image
Screenshot showing the necessary tool detected. Marked green only because it has been detected.

**Comment by sophieqguan** [comment]
oh mb I'm just blind sorry. Everything's happening too fast lmfao. 

Is it possible to change the 'Tool' header to something like, idk, 'Necessary Tools'? Or just something to better clarify what we want the users to do, cuz IMO 'Tool' can mean tools that's alrdy been detected, tools that are necessary, all the available tools, etc.

**Comment by Frankushima** [comment]
I'm noticing that the width for the list seems to change depending on if there's a tool in the tool list, which is something we might want to fix before merging. Other than that the functionality seems fine.

**Comment by aaron-sgy** [comment]
> oh mb I'm just blind sorry. Everything's happening too fast lmfao.
> 
> Is it possible to change the 'Tool' header to something like, idk, 'Necessary Tools'? Or just something to better clarify what we want the users to do, cuz IMO 'Tool' can mean tools that's alrdy been detected, tools that are necessary, all the available tools, etc.

Okay I can change the header.

**Comment by aaron-sgy** [comment]
> I'm noticing that the width for the list seems to change depending on if there's a tool in the tool list, which is something we might want to fix before merging. Other than that the functionality seems fine.

Which list are you referring to? If it is the `unwant_tools_tkinter_list` you are referring to, it is intended behavior because we have to delete/destroy any tkinter label no longer needed for any unwanted tools no longer detected so that it doesn't show "`doubleBracket X`"on the "Tool" Tab.

But if it is the `tools_list` you are referring to, that shouldn't be changed.

**Comment by Frankushima** [comment]
> > I'm noticing that the width for the list seems to change depending on if there's a tool in the tool list, which is something we might want to fix before merging. Other than that the functionality seems fine.
> 
> Which list are you referring to? If it is the `unwant_tools_tkinter_list` you are referring to, it is intended behavior because we have to delete/destroy any tkinter label no longer needed for any unwanted tools no longer detected so that it doesn't show "`doubleBracket X`"on the "Tool" Tab.
> 
> But if it is the `tools_list` you are referring to, that shouldn't be changed.

Okay in that case we can merge it, I might end up moving the GUI elements in a later change where I'll fix some issues like the scrollbar and scaling stuff. Just lemme know when ur ready on Slack

**Pull request merged**
